### ISSUE TITLE
"header" aliases have been removed in markdown-cli2

### ISSUE THREAD

**Issue by chadfawcett** [github/markdownlint-github#109]
We recently [updated `markdownlint-cli2` on The Hub](https://github.com/github/thehub/pull/16784) and noticed we started receiving increased errors related to headings. I dove into why and noticed that [markdownlint-cli2 has removed the rule aliases that use the word "header"](https://github.com/DavidAnson/markdownlint/commit/a9a77940c5502e21ed0b2a3ac5976dbcc0d5c52a) in favour of "heading".

As per the commit message, "header" aliases were deprecated in `v0.9.0`. I checked your [package.json and saw you're depending in `v0.13.0` ](https://github.com/github/markdownlint-github/blob/efa892f88c1356443a9f32585f8e923adc9c0620/package.json#L23)but still have [rules with the "header" alias](https://github.com/github/markdownlint-github/blob/efa892f88c1356443a9f32585f8e923adc9c0620/.markdownlint-cli2.cjs#L6).

**These rules should be updated to use "heading" instead of "header".**

**Comment by khiga8** [comment]
Hey @chadfawcett! Thank you for your contribution and fixing this!

I've just cut a new release - https://github.com/github/markdownlint-github/releases/tag/v0.6.3!
